Use github api for luda editor
NamseEnt/namseent pull request #286
Opened 2022-07-22 11:24 UTC by bigfoodK

2022-07-22 12:41 UTC, bigfoodK commented on luda-editor/luda-editor-client/src/app/sequence_list/mod.rs
> +}
Lock sequence first, then open editor

2022-07-22 12:41 UTC, bigfoodK commented on luda-editor/luda-editor-client/src/app/sequence_list/ops/sync_sequences_from_google_spreadsheet.rs
>  }
save sequences one by one, not in parallel.
Conflict may occur when a write api is requested at the same time.
However, we don't have strategy to respond the conflict.
So we save the sequences  one by one.

2022-07-22 12:41 UTC, bigfoodK commented on luda-editor/luda-editor-client/src/app/storage/storage.rs
> +    + GithubStorageCharacterImagePathsGet
Suuuuper long trait.
This is to divde the impls into several files while using one trait for easy mocking.

below is impossible for now.
``` rust
trait Trait {
  fn a();
  fn b();
}
struct Struct;

// a.rs
impl Trait for Struct {
  fn a() {}
}

// b.rs
impl Trait for Struct {
  fn b() {}
}
```

2022-07-22 12:41 UTC, bigfoodK commented on luda-editor/luda-editor-client/src/app/types/app_context.rs
> +}
`camera_angle_image_loader` is exactly same as `namui's image_loader`. But it uses `GithubStorage` instead.

2022-07-22 12:41 UTC, bigfoodK commented on luda-editor/luda-editor-client/src/app/authentication/authentication.rs
> +}
This is the part that needs to be replaced before it is merged.

2022-07-22 12:45 UTC, bigfoodK commented on luda-editor/luda-editor-client/src/app/authentication/authentication.rs
> +}
Can I create a repository `luda-editor-storage` under namseent org?

2022-07-22 13:49 UTC, namse commented
@bigfoodK If we decide to use namseent repository's branch for this system, what's the props and cons againt making other new repo?

2022-07-22 14:14 UTC, bigfoodK commented
**pros**
We can use just one repo. I don't know if this will be adventage.

**cons**
This is just a resource, not a code and It will not be merged into master. So we won't take monorepo's merits.
While using this app a huge amount of commit history will be piled up. I think it's better to isolate this in another repo.

2022-07-22 14:18 UTC, bigfoodK commented on luda-editor/luda-editor-client/src/app/storage/storage.rs
> +    + GithubStorageCharacterImagePathsGet
`StorageSequenceLockStateGet` name fixed.

2022-07-22 14:20 UTC, bigfoodK commented on luda-editor/luda-editor-client/src/app/storage/storage.rs
> +    + GithubStorageCharacterImagePathsGet
Internal traits (GithubStorageMetaGet, ...) are not exposed outside GithubStorage.

2022-07-22 15:39 UTC, namse commented
> This is just a resource, not a code and It will not be merged into master. So we won't take monorepo's merits.
I think it's a good merit because we can manage some resources without merging into master. If we make another repo, we have to manage new repository, so management point increases.

> While using this app a huge amount of commit history will be piled up. 
We can remove commits using github action interval jobs, kind of clean-up jobs.


Q. What about the permission of github? what kind of permission the user should have actually? Is it possible to divide the permission by branch?

2022-07-23 04:59 UTC, bigfoodK commented
The user needs permission to push commit directly to the target branch.
GitHub does not seem to have a function to manage user permission by branch. However, there is a function that prevents committing directly to the branch.
What scenario do you have in mind?

2022-07-23 13:32 UTC, namse commented
We can make a protected branch for this luda-editor and allow only some people to push their commit.
There is 'team' in github organization, so let's put editor people in that team.

2022-07-23 13:33 UTC, namse commented
I think luda-editor developer needs to use another branch when they want to test codes. Is it possible?

2022-07-23 20:13 UTC, namse requested changes

2022-07-23 20:18 UTC, namse commented
I think it's not a good idea to push this codes to master before making sure about git and repository strategy.
There are big problem about current concept.

If user A and B are trying to push new commit to master branch at the same time(or not very same time but if they fetched master branch with the same reference), they must make conflict even they try to write different files.
That's because branch only have 1 HEAD ref.

That mean, we maybe have to have each branch per each file. Then, it's not a good idea to use namseent repo for this because that will make too much of branches.

So, before making sure strategy, I suggest push this codes into different branch, not master. I think it's not ready. @bigfoodK

2022-07-24 07:08 UTC, bigfoodK commented on luda-editor/luda-editor-client/src/app/github_api/delete_file.rs
> +impl GithubAPiClient {
Thx!

2022-07-24 07:51 UTC, bigfoodK commented on luda-editor/luda-editor-client/src/app/authentication/authentication.rs
> +    })
Oh, I'll try it.

2022-07-24 19:19 UTC, namse commented
@bigfoodK  During this weekend, I considered many options and I think keep going with github as luda-editor's storage is a proper way to go.

So I made a new repository https://github.com/NamseEnt/luda-editor-storage for this.

I want to change the storage algorithm using other API like `git database api` for better usage.

Do you want to let me edit storage algorithm in PR now, or do you want to review in separated PR? I'll probably share the design documentation for the new algorithm first.

2022-08-19 08:39 UTC, namse commented
PR Content Merged into #313 so I close this PR.

2022-08-19 08:39 UTC, closed without merging