Impl tryfrom for Id
NamseEnt/namseent pull request #337
Opened 2022-09-21 07:50 UTC by bigfoodK

# What
impl TryFrom<&str> for `Id`.

# Why
There is function that create random `Id` before.
But there is no way to create pre-assigned `Id` outside the namui.

2022-09-21 07:51 UTC, bigfoodK commented on namui/src/namui/random/nano_id.rs
> +#[cfg(target_family = "wasm")]
Just moved from mod.rs

2022-09-21 07:55 UTC, namse commented
@bigfoodK When did you use try_from for Id? I guess that's not a good idea to write/read Id in string in hexadecimal because it will be too long.

2022-09-21 08:38 UTC, namse commented
base64 or 16 byte id instead 512 bit.

2022-09-21 08:41 UTC, namse commented
Anyway, Display is not for data serialization. Use serde or make it shorter and use raw buffer.

2022-09-21 09:41 UTC, namse requested changes
> Use serde or make it shorter and use raw buffer

Request changes. Review rejected.

2022-09-21 09:48 UTC, bigfoodK commented
base64 looks good. I will try that

2022-09-21 09:56 UTC, namse commented
@bigfoodK Change it 12 byte or 16 bytes, it seems too long for identification. uuid even use 16 bytes.

2022-09-21 12:57 UTC, namse commented
OK Sure, Let me know when you are ready to get review

2022-09-23 06:52 UTC, namse commented
@bigfoodK is it still needed to use TryFrom?

2022-09-23 07:05 UTC, bigfoodK commented
@namse Yes. For creating non-random Id from out of namui

2022-09-23 07:19 UTC, namse commented
@bigfoodK Do they exchange id information using string? why not just u8 slice?

2022-09-23 07:28 UTC, bigfoodK commented
@namse No. but developer need to create non-random Id for testing or level design.
Using a single line of base64 string would be more readable and editable than a u8 slice.

2022-09-23 07:37 UTC, namse commented
I'm confused as to what is the difference between nanoid and nanoid. Should I deprecate the nanoid side?

2022-09-23 07:43 UTC, namse commented
What I expected to Id is Copy impl. To make it possible, I used fixed sized u8 array. So I'm confused because you are trying to make it string.

2022-09-23 08:21 UTC, bigfoodK commented
I will not exchange Ids in state of String.
But I will use str to creating non-random Id.
ex)
```rust
let pre_assigned_id_for_test: Id = Id::from("ZdNAI2qYjIKZ/030AbSxGw");
```

2022-09-23 10:16 UTC, namse commented on namui/src/namui/random/id.rs
> +}
Please update here with below string type.

2022-09-23 15:14 UTC, namse commented on namui-animation-editor/src/time_point_editor/line_edit_window/render/mod.rs
> +        let id_interpolations = ImageInterpolation::iter()
I hate below code, will fix dropdown props next time.

2022-09-23 15:14 UTC, namse commented on namui/src/namui/common/text/multiline_caret.rs
> +                let last = caret_positions.last().unwrap().clone();
Error since new rust version.

2022-09-23 15:14 UTC, namse commented on namui/src/namui/skia/web/canvas_kit/mod.rs
> +#![allow(unused_doc_comments, dead_code)]
It shows previous PR merged code.
I made ticket about this.
https://support.github.com/ticket/personal/0/1807703

2022-09-23 15:15 UTC, namse commented
@bigfoodK Make a review please. then I will make a final confirm.

2022-09-24 00:36 UTC, bigfoodK commented on luda-editor/client/src/pages/sequence_edit_page/loaded/components/character_edit_modal/render/character.rs
> +                                (*character_id == character.id(), Some(text))
It's good, but it's not necessary.

2022-09-24 01:26 UTC, bigfoodK commented on namui/src/namui/random/uuid.rs
> +    fn try_from_base64_str() {
Maybe we should change test name.

2022-09-24 07:50 UTC, namse approved these changes

2022-09-24 08:00 UTC, merged