Load all images on start
NamseEnt/namseent pull request #492
Opened 2023-02-05 08:35 UTC by bigfoodK

2023-02-05 13:30 UTC, namse requested changes

2023-02-05 13:30 UTC, namse commented on luda-adventure/src/app/game/image_loader.rs
> +        };
should become Failed state?

2023-02-06 00:09 UTC, bigfoodK commented on luda-adventure/src/app/game/image_loader.rs
> +        };
Yes it should.

2023-02-06 01:03 UTC, namse approved these changes

2023-02-06 01:03 UTC, merged