Add graphic list view
NamseEnt/namseent pull request #673
Opened 2023-09-12 13:01 UTC by bigfoodK

2023-09-12 13:07 UTC, namse commented
Did you handled ctrl+z and ctrl+y or ctrl+shift+z for un/redo?

2023-09-12 14:19 UTC, bigfoodK commented
> Did you handled ctrl+z and ctrl+y or ctrl+shift+z for un/redo? Please put that function.

I didn't know that. But `un/redo` seems to be working.

2023-09-12 14:20 UTC, namse commented
Please check that

2023-09-13 05:32 UTC, bigfoodK commented
Yeah, It definitely works.
It will be handled [here](https://github.com/NamseEnt/namseent/blob/73a7086d14dddb5a5835ea0c8fc72d084ac34dcc/luda-editor/client/src/pages/sequence_edit_page/components/cut_editor/background_with_event.rs#L104-L107)

2023-09-13 09:05 UTC, namse requested changes

2023-09-13 10:53 UTC, bigfoodK commented on luda-editor/client/src/pages/sequence_edit_page/components/graphic_list_view/graphic_list_item.rs
> +                    })(wh, ctx);
Ah, you mean `namui_prebuilt::typography::body::left`. right?
I will do this now

2023-09-13 14:24 UTC, bigfoodK commented on luda-editor/client/src/pages/sequence_edit_page/components/side_bar/mod.rs
> +                        on_event: Box::new(|event| on_event(Event::MemoListView(event))),
fixed

2023-09-13 14:26 UTC, namse approved these changes
LGTM

2023-09-13 14:26 UTC, bigfoodK commented on luda-editor/client/src/pages/sequence_edit_page/components/graphic_list_view/mod.rs
> +                    },
Not the best but reduced nest

2023-09-13 14:45 UTC, merged