Split psd-sprite and psd-sprite-render crate
NamseEnt/namseent pull request #913
Opened 2024-08-20 11:35 UTC by bigfoodK

2024-08-20 11:45 UTC, namse requested changes

2024-08-20 11:45 UTC, namse commented on luda-editor/psd-sprite-render/Cargo.toml
> +[dependencies]
Remove unused crates please

2024-08-20 12:08 UTC, bigfoodK commented on luda-editor/psd-sprite-render/Cargo.toml
> +[dependencies]
All the crates are being used

2024-08-21 07:51 UTC, namse approved these changes

2024-08-21 07:51 UTC, merged