[LudaEditor] Server - Episode Editor and Transaction Abort Reason
NamseEnt/namseent pull request #937
Opened 2024-09-06 13:10 UTC by namse

1. Implements episode editor apis
2. Supports passing transaction abort reason

2024-09-06 13:29 UTC, namse commented
#934 reverted forked rusqlite changes, so I re-revert it in this pr

2024-09-06 17:57 UTC, bigfoodK requested changes

2024-09-06 17:57 UTC, bigfoodK commented on luda-editor/third-party-forks/psd
It looks like it's reverting https://github.com/NamseEnt/psd/commit/506abf22efa0048839db7ca247fb9bbeef13d1ff.

2024-09-07 11:58 UTC, namse commented on luda-editor/third-party-forks/psd
fucking hate git

2024-09-07 12:01 UTC, bigfoodK approved these changes

2024-09-07 12:59 UTC, merged