Support big data for insert-js
NamseEnt/namseent pull request #948
Opened 2024-09-11 02:22 UTC by namse

@bigfoodK please test this with psd.

2024-09-11 16:04 UTC, bigfoodK requested changes
Error occurs.
```text
Uncaught (in promise) Error: Unknown event! {"type":"insert-js/request-data-buffer","jsId":["u32",0],"bufferLen":["u32",4],"requestId":["u32",0]}
    at NewEventSystemHandleOnMainThread.sendEvent (newEventSystem.ts:147:23)
    at window.namui_onData (insertJs.ts:72:30)
    at namui_sendData (<anonymous>:2:24)
    at inputElement.onchange (<anonymous>:43:5)
```

Maybe changes of `namui-cli/webCode/src/newEventSystem.ts` are missing.

2024-09-11 16:08 UTC, namse commented
Please test again

2024-09-11 17:08 UTC, bigfoodK requested changes

2024-09-11 17:08 UTC, bigfoodK commented on namui/namui-cli/webCode/src/insertJs.ts
> +        OnInsertJsDataBuffer({
```suggestion
        onInsertJsDataBuffer({
```

2024-09-11 17:08 UTC, bigfoodK commented on namui/namui-cli/webCode/src/insertJs.ts
> +            new Uint8Array(data).set(new Uint8Array(memory.buffer, bufferPtr));
```suggestion
            new Uint8Array(memory.buffer, bufferPtr).set(new Uint8Array(data));
```

Reversed

2024-09-12 01:30 UTC, bigfoodK approved these changes

2024-09-12 01:33 UTC, merged